#!/bin/sh
echo "start------cat /etc/os-release------"
cat /etc/os-release
echo "end------cat /etc/os-release------"
echo "start------docker --version------"
docker version
echo "end------docker --version------"

docker run --rm --privileged multiarch/qemu-user-static:register --reset
# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
